name: 'dbt_full_testing_suite'
version: '1.0.0'
config-version: 2
profile: 'dbt_testing'
model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  dbt_full_testing_suite:
    staging:
      +materialized: view
      +tags: ["staging"]
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +tags: ["marts"]
